# Generated by Django 3.2.5 on 2021-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=10)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('phone_number', models.CharField(max_length=13)),
                ('email_address', models.EmailField(max_length=254)),
                ('identification_card', models.CharField(max_length=13)),
                ('nationality', models.CharField(max_length=15)),
                ('language', models.CharField(choices=[('E', 'English'), ('K', 'Kiswahili'), ('F', 'French')], max_length=18)),
                ('resume', models.FileField(upload_to='')),
                ('course', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=15)),
                ('days', models.CharField(max_length=5)),
                ('salary', models.FloatField()),
                ('contract', models.FileField(upload_to='')),
                ('company', models.CharField(max_length=15)),
            ],
        ),
    ]
