# Generated by Django 3.2.7 on 2021-09-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210907_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
