# Generated by Django 3.2.5 on 2021-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('description', models.DateField(null=True)),
                ('trainer', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
