# Generated by Django 3.2.7 on 2021-09-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='trainer',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
