# Generated by Django 3.2.5 on 2021-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=12, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Others')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_id', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda'), ('S', 'Sudan'), ('S', 'SouthSudan')], max_length=15, null=True)),
                ('language', models.CharField(blank=True, choices=[('E', 'English'), ('K', 'Kiswahili'), ('F', 'French')], max_length=18, null=True)),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='')),
                ('health_records', models.FileField(blank=True, null=True, upload_to='')),
                ('admission_date', models.DateField(blank=True, max_length=15, null=True)),
                ('class_name', models.CharField(blank=True, max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, max_length=14, null=True)),
                ('guardian_phonenumber', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=20, null=True)),
                ('academic_year', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='images')),
            ],
        ),
    ]
