# Generated by Django 3.2.4 on 2021-09-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_image',
            new_name='image',
        ),
    ]
